### ISSUE TITLE
Collaboration with Other School Organizations

### ISSUE THREAD

**Issue by anthonygraca** [cppignite/ignite-hq#11]
Mostafa - Talk to SheCodes
Anthony - Talk to CEIS

**Comment by anthonygraca** [comment]
SIAM (math club) and Game Dev want to collab with Ignite. The members of the Pre-Optometry club are looking for volunteering hours

**Comment by anthonygraca** [comment]
Talked to Kim from SheCodes to potentially work with them for their FWD conference. Potentially working with Science Council to hold a workshop for all of College of Science

**Comment by sunyu912** [comment]
Great. She did an internship in Girls Who Code in the summer which sounds like a good program. I am also asking her and see if we could get some lesson plans.

**Comment by anthonygraca** [comment]
Not Needed
