### ISSUE TITLE
Figure out this week's lession

### ISSUE THREAD

**Issue by dave-luk** [cppignite/ignite-hq#16]
We have 2 returners at Los Altos high school. also, we have 3 new students, how can we make our lesson engaging?

**Comment by sunyu912** [comment]
How many total students are in the class?

**Comment by mostafavahidi** [comment]
Right now only 5 students.

**Comment by dave-luk** [comment]
for the first lesson, the 2 returners are not that engaged in the lesson since they already have seen the lesson.

**Comment by mostafavahidi** [comment]
yes, that's something that we need to discuss in Wednesday's meeting. How to keep the returning 2 engaged in the lesson plan
