### ISSUE TITLE
Send Emails to Parents and Students about Change in Schedule

### ISSUE THREAD

**Issue by anthonygraca** [cppignite/ignite-hq#17]
CONTEXT: When we sent out out fliers, the schedule of ignite lessons left are: 1/5, 1/12, 1/19, 1/26, 2/2, 2/9

The kids are still in school this week, we need to email them that we are not going to be teaching a lesson on the 12/15. Also, we need to cancel the lesson on 1/5 because the students are still on winter break. I checked the school's calendar and all the other days will not conflict with "day offs"

Please email the parents, students, and principal of the remaining dates: 1/12, 1/19, 1/26, 2/2, 2/9 and also remind them that we will not be having a lesson this Friday.

**Comment by sunyu912** [comment]
Thanks Anthony!

**Comment by anthonygraca** [comment]
Good Job @Dimipilo92, it looks like the Middle School students are informed.
I sent out an email to the Elementary School parents + principal.

**Comment by anthonygraca** [comment]
@Dimipilo92 Also ask the school admin about missing students and ask them how we can re-engage with them when we return on jan 12th

**Comment by anthonygraca** [comment]
done
