### ISSUE TITLE
Fill out Signature Card

### ISSUE THREAD

**Issue by anthonygraca** [cppignite/ignite-hq#28]
ASI lost our signature card

**Comment by sunyu912** [comment]
Ok, what should I do?

**Comment by anthonygraca** [comment]
I'll print out a copy and have you sign it today @sunyu912. For @dave-luk and @mostafavahidi, going to scan it into a pdf and send them a copy so they can sign it. Then they will scan it and send it back to me

**Comment by sunyu912** [comment]
Got it! Thanks guys.

**Comment by anthonygraca** [comment]
I redownloaded the signature card that we turned in at the beginning of the year and I gave that form to ASI. I'm waiting for a reply from them to see if they accept it
