### ISSUE TITLE
Create Instructions on How To Install an IDE in their Home Computers

### ISSUE THREAD

**Issue by anthonygraca** [cppignite/ignite-hq#31]
For Java and Python and create a wiki page basically walking through the students step by step

**Comment by anthonygraca** [comment]
@cppignite/high_school @cppignite/middle_school I need to know if anyone is working on this. If I don't get any volunteers, I am going to write up a wiki page teaching the kids how to use VIM and how to compile/run on the Command Line

**Comment by baoqchau** [comment]
That will be pretty hardcore for these kids though.

**Comment by anthonygraca** [comment]
Done. Thanks for getting it done, @baoqchau
