### ISSUE TITLE
Enter Schedule for Winter 2018

### ISSUE THREAD

**Issue by anthonygraca** [cppignite/ignite-hq#32]
@cppignite/elementary_school @cppignite/high_school @cppignite/middle_school

**Comment by sunyu912** [comment]
This is a great idea. We should have a shared google calendar for everyone.

**Comment by anthonygraca** [comment]
@cppignite/elementary_school @cppignite/high_school @cppignite/middle_school 

Here are the links. Please fill out your respective team

Elementary - https://goo.gl/XgLDAp
Middle - https://goo.gl/nR16bE
High - https://goo.gl/BcEqMG

**Comment by dave-luk** [comment]
Done
