### ISSUE TITLE
Create a Lesson Plan for Week 1

### ISSUE THREAD

**Issue by anthonygraca** [cppignite/ignite-hq#33]
@cppignite/high_school - Create a wiki page for week 1. Submit sample code + Exercises onto repo

**Comment by 392781** [comment]
Finished half of the wiki.  Could use some improvements.  Gonna jump back in later to add a few things

**Comment by anthonygraca** [comment]
great job ron!

**Comment by anthonygraca** [comment]
Let's move on to week 2. We will put exercises in later
