### ISSUE TITLE
Create mini activities and one big activity at the end

### ISSUE THREAD

**Issue by anthonygraca** [cppignite/ignite-hq#35]

**Comment by sunyu912** [comment]
Great idea!

**Comment by anthonygraca** [comment]
@slinky102 Brainstorm for week 2
@mostafavahidi Implement activities for week 1

**Comment by anthonygraca** [comment]
@slinky102, I uploaded a few ideas. We'll discuss in the meeting.
@mostafavahidi, good work

**Comment by mostafavahidi** [comment]
@anthonygraca  why would you do that? I have the majority of it done. Just need one more day.. smh lol

**Comment by mostafavahidi** [comment]
@anthonygraca also we should've discussed these issues in the meeting before you close them or transfer them to someone else.

**Comment by anthonygraca** [comment]
@mostafavahidi, commit the code that you have

**Comment by mostafavahidi** [comment]
@anthonygraca done.
