### ISSUE TITLE
Design the SRPK Syllabus and the Team

### ISSUE THREAD

**Issue by sunyu912** [cppignite/ignite-hq#7]

**Comment by sunyu912** [comment]
@mostafavahidi Make sure you play around with the robot this week, and get some thoughts on this when we meet next week.

**Comment by sunyu912** [comment]
@dave-luk Do you have a robot? If not, could you stop by in the afternoons so that I can give you one?

**Comment by sunyu912** [comment]
@mostafavahidi @dave-luk This would be the new program and let's get things prepared soon.

**Comment by anthonygraca** [comment]
Syllabus posted on flyer and on slack. check elementary school channel for flyer
